### ISSUE TITLE
Lost all devices

### ISSUE THREAD

**Issue by sq4bja** [bbqkees/ems-esp-domoticz-plugin#8] opened 2020-02-06 18:20 UTC
Hi,
After I add new plugin into newerst domoticz beta, and add all devices from ESP plugin i lost all devices (include EMS-ESP). List is blank, but everything works fine. But i can`t add another device, and i can`t see other. Removing plugin doesn`t help. Device list is blank.
Tom

**Comment by sq4bja** [comment] 2020-02-06 18:45
In logs i see only one error: 2020-02-06 19:45:08.089 Error: WebServer PO exception occurred : 'stoull'

**Comment by bbqkees** [comment] 2020-02-06 20:37
I can't reproduce this.
If I check the Domoticz forum this sometimes happens after adding a new hardware.
Try removing the hardware from the database itself and see if the devices have returned.

**Comment by sq4bja** [comment] 2020-02-06 20:56
Ok, try to add EMS plugin, and remove EMS-ESP from network, or disconnect EMS rail. It happens only with EMS plugin.

**Comment by bbqkees** [comment] 2020-02-07 07:41
What system are you running Domoticz on?

**Comment by sq4bja** [comment] 2020-02-07 07:50
Raspberry 3B+, Raspbian Buster. After connecting EMS rail, everything works OK, but only few errors in logs:

 2020-02-07 03:31:28.726 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-02-07 03:31:28.726 Error: (BUDERUS) ----> Line 961 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-07 03:31:28.726 Error: (BUDERUS) ----> Line 900 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-07 03:31:28.726 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-02-07 03:31:28.726 Error: (BUDERUS) ----> Line 932 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish
2020-02-07 03:31:38.749 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-02-07 03:31:38.749 Error: (BUDERUS) ----> Line 961 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-07 03:31:38.749 Error: (BUDERUS) ----> Line 900 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-07 03:31:38.749 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-02-07 03:31:38.749 Error: (BUDERUS) ----> Line 932 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish

**Comment by bbqkees** [comment] 2020-02-07 08:36
How did you install the plugin? With a git clone command?

**Comment by sq4bja** [comment] 2020-02-07 08:36
Yes. Domoticz version is 4.11670

**Comment by bbqkees** [comment] 2020-02-07 08:43
A NameError means that its missing something.
Here it runs fine.

What is your Python version? (Domoticz->Setup->About).
Have you selected 'Accept new Hardware Devices' before starting the plugin?

**Comment by sq4bja** [comment] 2020-02-07 08:44
Version: 4.11670
Build Hash: f6af0fa0c
Compile Date: 2020-02-02 12:21:53
dzVents Version: 2.5.7
Python Version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]

**Comment by lmdecroos** [comment] 2020-02-07 22:11
I have the same error at startup, but the value status "ignWork" is updated in Domoticz

2020-02-07 22:49:32.483 Status: (EMS) Initialized version 0.9
2020-02-07 22:49:32.669 Error: (EMS) 'onMessage' failed 'NameError'.
2020-02-07 22:49:32.669 Error: (EMS) ----> Line 961 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-02-07 22:49:32.669 Error: (EMS) ----> Line 900 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-02-07 22:49:32.669 Error: (EMS) ----> Line 113 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py'
2020-02-07 22:49:32.669 Error: (EMS) ----> Line 932 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-02-07 22:49:42.585 (EMS) onMessage called with: PINGRESP 

I'm running the stable version of Domoticz 
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]

**Comment by bbqkees** [comment] 2020-02-08 15:14
Given I only changed a few words in the plugin the last update it seems unlikely that it is the cause.
https://github.com/bbqkees/ems-esp-domoticz-plugin/commit/a10fabe32a64d6fcc563a3e8fe6ad3b90fe5c1dd

When did the problem start exactly? After updating the plugin of after updating Domoticz?

**Comment by lmdecroos** [comment] 2020-02-08 15:22
I updated the plugin yesterday, based on the bug report.
i have not updated domoticz

Had a look in code an can’t find any reason for the errors as initiating the plug-in

**Comment by bbqkees** [comment] 2020-02-08 15:25
Ok do you know which previous version of the plugin you were running?

**Comment by lmdecroos** [comment] 2020-02-08 15:33
version 0.7

**Comment by bbqkees** [comment] 2020-02-10 10:07
The update from 0.7 tot 0.8 was significant though.
https://github.com/bbqkees/ems-esp-domoticz-plugin/commit/31454d27dc374a3a641b5dfdf1040d585c5ae9a7#diff-66c71ea3faaa52c277917c951aa67921

Can you revert to 0.7 and see if it works again?
Did you enable 'adding new hardware' after updating the plugin?

**Comment by lmdecroos** [comment] 2020-02-10 17:48
I reverted back to version 0.7 and had no error at loading the plugin
I have no copy of version 0.8 to test

**Comment by bbqkees** [comment] 2020-02-11 07:57
So in 0.8 a large number of new devices are added.
Perhaps some of these devices are not created in your case.

because you updated before to 0.9, you should still have all these new devices, even if you revert to a previous version of the plugin.

Can you check if you have for instance unit 26 'ww desired temperature' in the Domoticz device list?

**Comment by lmdecroos** [comment] 2020-02-11 18:02
I think I have them all :

1 - 39
71 - 73
111 - 113
121 - 123
131- 133
141 - 143
151 - 153
161 - 163
221 - 225

**Comment by bbqkees** [comment] 2020-02-18 16:09
I'm still unsure whats causing this.
To revert to 0.7 use the following file:
https://github.com/bbqkees/ems-esp-domoticz-plugin/blob/4f3f21e82cbe9f2a16028663b5816325eba4ff22/plugin.py

**Comment by bbqkees** [comment] 2020-02-18 19:06
Maybe it is not a problem with this plugin itself.
Can you try to delete the appcache etc?

https://www.domoticz.com/forum/viewtopic.php?f=6&t=31379
https://www.domoticz.com/forum/viewtopic.php?f=6&t=31010

**Comment by sq4bja** [comment] 2020-02-20 13:51
After upgrade to latest dev version i got the same issue like before in Domoticz log:

 2020-02-20 14:48:29.056 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-02-20 14:48:29.056 Error: (BUDERUS) ----> Line 999 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-20 14:48:29.056 Error: (BUDERUS) ----> Line 938 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-20 14:48:29.056 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-02-20 14:48:29.056 Error: (BUDERUS) ----> Line 970 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish
2020-02-20 14:48:29.057 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-02-20 14:48:29.057 Error: (BUDERUS) ----> Line 999 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-20 14:48:29.057 Error: (BUDERUS) ----> Line 938 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-02-20 14:48:29.057 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-02-20 14:48:29.057 Error: (BUDERUS) ----> Line 970 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish 

This is showing, when the plugin is starting (after reboot Domoticz or update plugin in domoticz hardware).
Newest: Domoticz beta, Raspbian Buster, Pi3B+

Tom

**Comment by bbqkees** [comment] 2020-03-02 15:07
Can you check the dev branch if it makes any difference now?

**Comment by sq4bja** [comment] 2020-03-02 16:31
No, errors are still there. It shows when the plugin is loading. 

>  2020-03-02 17:28:49.100 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 822 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 761 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 793 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish
2020-03-02 17:28:49.100 Error: (BUDERUS) 'onMessage' failed 'NameError'.
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 822 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 761 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 113 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py', function onMessage
2020-03-02 17:28:49.100 Error: (BUDERUS) ----> Line 793 in '/home/pi/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py', function onMQTTPublish

**Comment by lmdecroos** [comment] 2020-03-02 16:44
same here :(

2020-03-02 17:42:09.047 Status: (EMS) Entering work loop.
2020-03-02 17:42:09.048 Status: (EMS) Initialized version 1.0b4
2020-03-02 17:42:09.216 Error: (EMS) 'onMessage' failed 'NameError'.
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 822 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 761 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 113 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 793 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-03-02 17:42:09.216 Error: (EMS) 'onMessage' failed 'NameError'.
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 822 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 761 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 113 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/mqtt.py'
2020-03-02 17:42:09.216 Error: (EMS) ----> Line 793 in '/home/lmd/domoticz/plugins/ems-esp-domoticz-plugin/plugin.py'

**Comment by bbqkees** [comment] 2020-03-05 14:19
I tried Domoticz on Jessie and Stretch on a Raspberry Pi 2B and no issues here.
Even with multiple instances of the same plugin at the same time.
Are you on Buster?
I ordered a new Pi 4B to test with Buster.

**Comment by sq4bja** [comment] 2020-03-05 14:50
Im on buster on pi3b+

**Comment by lmdecroos** [comment] 2020-03-05 16:05
same here buster PI3b+

**Comment by bbqkees** [comment] 2020-03-05 16:39
Ok. I will test it with Buster when my new test Pi arrives next week.

**Comment by bbqkees** [comment] 2020-03-10 21:29
I tested today with a new Pi 4 on Buster with the latest Domoticz stable and beta (4.11780) and I can't reproduce it.
Keep in mind though the latest Domoticz versions may hide devices until you click on the small vertical bar on the left of the device list.
![device-bar](https://user-images.githubusercontent.com/10775682/76361086-86cd6d80-631e-11ea-9a84-89e9107f9e12.PNG)

**Comment by sq4bja** [comment] 2020-03-10 21:37
Try to push update button on EMS1 in hardware. Look into log - is there any errors from EMS-ESP plugin like here?
![obraz](https://user-images.githubusercontent.com/26671657/76361589-a1ecad00-631f-11ea-9125-c9d591c55577.png)

**Comment by bbqkees** [comment] 2020-03-10 21:44
No errors here.

Can you post a payload of all MQTT topics you have?
Maybe you have an parameter which is not in my system that causes this.

**Comment by sq4bja** [comment] 2020-03-10 21:51
Below payload from my MQTT server. I`m using newest EMS-ESP beta.

`{"wWComfort":"Eco","wWSelTemp":44,"wWDesinfectionTemp":70,"selFlowTemp":26,"selBurnPow":57,"curBurnPow":0,"pumpMod":68,"wWCircPump":255,"wWCiPuType":255,"wWCiPuMode":7,"outdoorTemp":7.5,"wWCurTmp":48.8,"wWCurFlow":0,"curFlowTemp":24.2,"wwStorageTemp2":48.8,"wWActivated":"on","wWOnetime":"off","wWDesinfecting":"off","wWReady":"off","wWRecharge":"off","wWTempOK":"on","wWCirc":"on","burnGas":"off","flameCurr":0,"heatPmp":"on","fanWork":"off","ignWork":"off","heating_temp":55,"pump_mod_max":100,"pump_mod_min":10,"wWHeat":"off","wWStarts":2356,"wWWorkM":46503,"UBAuptime":1094026,"burnStarts":4589,"burnWorkMin":315586,"heatWorkMin":269083,"ServiceCode":"0Y","ServiceCodeNumber":204}
qos : 0, retain : false, cmd : publish, dup : false, topic : home/ems-esp/boiler_data, messageId : , length : 710, Raw payload : 12334119876711110910211111411634583469991113444341198783101108841011091123458525244341198768101115105110102101991161051111108410110911234585548443411510110870108111119841011091123458505444341151011086611711411080111119345853554434991171146611711411080111119345848443411211710911277111100345854564434119876710511499801171091123458505353443411987671058011784121112101345850535344341198767105801177711110010134585544341111171161001111111148410110911234585546534434119876711711484109112345852564656443411987671171147010811111934584844349911711470108111119841011091123458505246504434119119831161111149710310184101109112503458525646564434119876599116105118971161011003458341111103444341198779110101116105109101345834111102102344434119876810111510511010210199116105110103345834111102102344434119878210197100121345834111102102344434119878210199104971141031013458341111021023444341198784101109112797534583411111034443411987671051149934583411111034443498117114110719711534583411110210234443410210897109101671171141143458484434104101971168010911234583411111034443410297110871111141073458341111021023444341051031108711111410734583411110210234443410410197116105110103951161011091123458535344341121171091129510911110095109971203458494848443411211710911295109111100951091051103458494844341198772101971163458341111021023444341198783116971141161153458505153544434119878711111410777345852545348514434856665117112116105109101345849485752485054443498117114110831169711411611534585253565744349811711411087111114107771051103458514953535654443410410197116871111141077710511034585054574856514434831011141181059910167111100101345834488934443483101114118105991016711110010178117109981011143458504852125
{"hc1":{"seltemp":21,"currtemp":21.5,"mode":"auto","modetype":"comfort"}}
qos : 0, retain : false, cmd : publish, dup : false, topic : home/ems-esp/thermostat_data, messageId : , length : 103, Raw payload : 123341049949345812334115101108116101109112345850494434991171141141161011091123458504946534434109111100101345834971171161113444341091111001011161211121013458349911110910211111411634125125
{"rssid":44,"load":1,"uptime":85458,"freemem":43,"tcpdrops":0,"mqttpublishfails":0}
qos : 0, retain : false, cmd : publish, dup : false, topic : home/ems-esp/heartbeat, messageId : , length : 107, Raw payload : 123341141151151051003458525244341081119710034584944341171121161051091013458565352535644341021141011011091011093458525144341169911210011411111211534584844341091131161161121179810810511510410297105108115345848125
{"wWComfort":"Eco","wWSelTemp":44,"wWDesinfectionTemp":70,"selFlowTemp":26,"selBurnPow":57,"curBurnPow":0,"pumpMod":68,"wWCircPump":255,"wWCiPuType":255,"wWCiPuMode":7,"outdoorTemp":7.5,"wWCurTmp":48.7,"wWCurFlow":0,"curFlowTemp":24.2,"wwStorageTemp2":48.7,"wWActivated":"on","wWOnetime":"off","wWDesinfecting":"off","wWReady":"off","wWRecharge":"off","wWTempOK":"on","wWCirc":"on","burnGas":"off","flameCurr":0,"heatPmp":"on","fanWork":"off","ignWork":"off","heating_temp":55,"pump_mod_max":100,"pump_mod_min":10,"wWHeat":"off","wWStarts":2356,"wWWorkM":46503,"UBAuptime":1094026,"burnStarts":4589,"burnWorkMin":315586,"heatWorkMin":269083,"ServiceCode":"0Y","ServiceCodeNumber":204}`

**Comment by bbqkees** [comment] 2020-03-10 22:22
Ok I tested those payloads here but no errors.

**Comment by bbqkees** [comment] 2020-03-12 08:56
Do you only have the NameError or is the device list still empty?

**Comment by sq4bja** [comment] 2020-03-12 14:29
Only error. Everething alse works fine. All devices are in the list. Only this error...

**Comment by bbqkees** [comment] 2020-03-12 15:40
Ok so I will close this issue as it was opened for the empty device list.
The single NameError at boot is not really problematic at this point.

**Closed as completed by bbqkees** 2020-03-12 15:40 UTC
